title: Test jupyter book
author: andreGismo
logo: img/logo.jpg

html:
  extra_footer: |
    <p>
    This all is just a ...<br><br>
    <img src='https://github.com/AndreGismo/jupyter-book-test/blob/main/img/logo.jpg'
    </p>
    
    
sphinx:
  config:
    html_show_copyright: false