title: Test jupyter book
author: andreGismo
logo: img/logo.jpg

html:
  extra_footer: |
    <p>
    This all is just a ...<br><br>
    <img src='C:\Users\andre\Documents\GitHub\JUPYTERBOOK_TEST\jupyter-book-test\img\logo.jpg'>
    </p>
    
    
sphinx:
  config:
    html_show_copyright: false
    
    
repository:
  url: https://github.com/AndreGismo/jupyter-book-test  
  branch: main
  
launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true